### ISSUE TITLE
Black screen when opening on muOS Loose Goose 2508.4

### ISSUE THREAD

**Issue by njjbjhbjhbhjbjhb** [andersmmg/app_downloader#5]
When opening on muOS Golden Goose 2508.3, it just goes to a black screen and then goes back to the Applications menu. Also, during installation, I saw "Skipping unsupported archive: opt". I also deleted the app already.

**Comment by andersmmg** [comment]
Are you using the latest version? It works on Golden Goose for me, the unsupported archive message can be ignored here. Also, do you have the runtime installed?

**Comment by andersmmg** [comment]
If you're using the latest and have the runtime installed, please send the log file and I'll take a look.

**Comment by njjbjhbjhbhjbjhb** [comment]
I am using the latest version. How do I check if I have the runtime? Also, where do I find the log file? Also, I deleted the app by using the built-in file manager, at /run/muos/storage/application and I deleted the "App Downloader" folder.

**Comment by andersmmg** [comment]
Log file will be in the port directory, you check and install runtimes inside PortMaster

**Comment by njjbjhbjhbhjbjhb** [comment]
Hello! I am sorry that I could not reply earlier. I lost my WiFi. I cannot find anything about log files, sorry. Maybe they were deleted. I got the runtime "Godot/FRT 4.1.3" but nothing happens. Still broken. Also, I never removed the .mux* file. There is also no icon.

**Comment by njjbjhbjhbhjbjhb** [comment]
I tried to install all the runtimes, but still broken.

**Comment by njjbjhbjhbhjbjhb** [comment]
Hello! I think the file is broken, because with all the runtimes installed and verified it is still broken.

**Comment by andersmmg** [comment]
I'll try to look into it, but I'm not sure what the issue is since it installs and runs just fine for me on the latest muOS

**Comment by njjbjhbjhbhjbjhb** [comment]
Okay, thank you! Also, the device i use is the Anbernic RG35XX Pro.

**Comment by njjbjhbjhbhjbjhb** [comment]
Hello! Has the problem been fixed?

**Comment by TheRealFame** [comment]
It doesn't seem like the issue had been fixed?

**Comment by andersmmg** [comment]
I've tried to look into it, but I haven't been able to reproduce it myself. It runs just fine on the latest and older muOS versions for me, so I'm not sure where to go from here to fix it. Have any of you been able to get logs from it?

**Comment by njjbjhbjhbhjbjhb** [comment]
Hello! I will try to install the application again and find any kind of logs.

**Comment by njjbjhbjhbhjbjhb** [comment]
I do not have access to my laptop right now, so I can't get the logs yet. I do have my phone but I do not have a pin to insert the SD card.

**Comment by njjbjhbjhbhjbjhb** [comment]
Sorry, I tried to insert my secondary SD card and searched "log," but there was nothing that was related to the App Downloader.

**Comment by TheRealFame** [comment]
> I've tried to look into it, but I haven't been able to reproduce it myself. It runs just fine on the latest and older muOS versions for me, so I'm not sure where to go from here to fix it. Have any of you been able to get logs from it?

Do you know where the logs directory is?

**Comment by njjbjhbjhbhjbjhb** [comment]
Hello! I have a question, is the log stored on the primary SD card or the secondary SD card?

**Comment by andersmmg** [comment]
> Hello! I have a question, is the log stored on the primary SD card or the secondary SD card?

It's stored next to wherever it's installed, it will depend on your setup where apps are installed. I believe by default it's SD1

**Comment by njjbjhbjhbhjbjhb** [comment]
I have no access to my laptop right now,  but later, I will try to search for logs on the primary SD card.

**Comment by njjbjhbjhbhjbjhb** [comment]
I have this image of some file, and it might be important.

**Comment by njjbjhbjhbhjbjhb** [comment]
![Messenger_creation_A8DE7282-72AF-40EB-9F8D-A64DCFB91907.jpeg](https://github.com/user-attachments/assets/f544bfe9-8ae4-4512-8eb7-dbbd373773ed)

**Comment by njjbjhbjhbhjbjhb** [comment]
Hello! I found where the log file is located. (The first SD card) I cannot send it now because I got a new SD card (secondary), and I am transferring my data from old to new. (I only have a built-in card reader and 1 USB to card adapter.)

**Comment by njjbjhbjhbhjbjhb** [comment]
Hello! I have the logs now.

[log.txt](https://github.com/user-attachments/files/23756254/log.txt)

**Comment by andersmmg** [comment]
Thank you, that does help me narrow it down. I'll see what I can do!

**Comment by njjbjhbjhbhjbjhb** [comment]
Hi! Is it fixed now?

**Comment by njjbjhbjhbhjbjhb** [comment]
Hi! Is it fixed now?

**Comment by JimScope** [comment]
The same thing happened to me @njjbjhbjhbhjbjhb and @TheRealFame. I connected the console to the Internet and it started working. @andersmmg, the problem must be that an initial data load is being performed and the request fails abruptly, causing a crash.

**Comment by JimScope** [comment]
@andersmmg I think this error only occurred in versions prior to v0.2.3 prerelease.

**Comment by andersmmg** [comment]
> [@andersmmg](https://github.com/andersmmg) I think this error only occurred in versions prior to v0.2.3 prerelease.

0.2.3 was released to hopefully fix the issue, which it did for me. I haven't had time to look into what could still be causing it still

**Comment by JimScope** [comment]
That version works

**Comment by njjbjhbjhbhjbjhb** [comment]
Hello! I will send a video of what happens if I try to use the app. (Also, it will be in a Google Drive link.)

**Comment by njjbjhbjhbhjbjhb** [comment]
Please ignore the music.
https://drive.google.com/file/d/1YarPHJG_sxNPNJ2a95MM8hJm1b1GqrvM/view?usp=drive_link

**Comment by JimScope** [comment]
@njjbjhbjhbhjbjhb That's strange. Are you using version 0.2.3?

**Comment by njjbjhbjhbhjbjhb** [comment]
@JimScope Yes. It is in the file name.

**Comment by njjbjhbjhbhjbjhb** [comment]
Hello! Is is fixed now?

**Comment by andersmmg** [comment]
Try this modified version, let me know how it goes:
https://limewire.com/d/uBaIM#RW6lZF0qqf

**Comment by PandorasMicrowave** [comment]
Hello, I have tested the modified version on loose goose 2508.4 and the issue remains the same, however, my log file has one less line.

[log.txt](https://github.com/user-attachments/files/24142615/log.txt)

I have the runtime installed and verified.

**Comment by njjbjhbjhbhjbjhb** [comment]
Hello! I tried the modified version, and it installs nothing. I also cannot check my runtimes anymore since PortMaster crashes when opening.

**Comment by njjbjhbjhbhjbjhb** [comment]
I have upgraded to muOS Loose Goose 2508.4 now. I have not tested it yet.

**Comment by njjbjhbjhbhjbjhb** [comment]
Hello! I have tested only the modified version and the non-modified one, both do not work.

**Comment by leginnosivad** [comment]
I also have the same issues as above. I have an RG40XXH running Loose Goose and tried to install 0.2.3 but I just get a black screen, then back to the app menu. 

I had the same issue with the last MU release too, I've tried adding it to archive manager on SD1 and SD2 but I get the same issue when installing from both locations.

**Comment by njjbjhbjhbhjbjhb** [comment]
Hello! Is it fixed yet?

**Comment by njjbjhbjhbhjbjhb** [comment]
Hi! Is it fixed yet?

**Comment by njjbjhbjhbhjbjhb** [comment]
Hello! Is it fixed?

**Comment by njjbjhbjhbhjbjhb** [comment]
Hello! Is it fixed?
